### ISSUE TITLE
Cannot run it

### ISSUE THREAD

**Issue by galuel** [eskopp/LiveChessCloud#13]
I succeeded in installation from Ubuntu 18.04 but it does not work

`~/.local/lib/python3.10/site-packages/LiveChessCloud$ LiveChessCloud --version`
`LiveChessCloud : commande introuvable`

Thank you for any advice

**Comment by eskopp** [comment]
Thank you for sharing your issue. There are several possible causes for the problem you've described, and I would like to offer some solutions. Before diving into the details, however, I must stress that both your operating system (Ubuntu 18.04) and the Python version you're using (Python 3.10) are significantly outdated.

### 1. **Outdated Software**
Ubuntu 18.04 reached its **End of Life (EOL)** in April 2023. This means it no longer receives security updates or official support, which poses significant security risks. I strongly recommend upgrading to a newer version of Ubuntu, ideally an LTS version such as Ubuntu 22.04.

Additionally, Python 3.10 is not the latest version, and there may be compatibility issues with newer packages. Consider upgrading to the latest stable Python version (currently Python 3.12).

### 2. **Fixing the Path Issue**
The issue that `LiveChessCloud` is not found likely stems from the installation path not being included in your system's `$PATH`. To resolve this, you can try running the program directly using the full path:

```bash
~/.local/lib/python3.10/site-packages/LiveChessCloud/LiveChessCloud --version
```

If this works, you should add the path permanently to your $PATH environment variable:

```bash
export PATH=$PATH:~/.local/lib/python3.10/site-packages/LiveChessCloud/
```


Add this line to your ~/.bashrc or ~/.bash_profile to make it permanent, and reload the file:

```bash
source ~/.bashrc
```
### 3. 3. Verify Installation
Ensure that LiveChessCloud was installed correctly. If you used pip, you can check if the package is present with the following command:

```bash
pip show LiveChessCloud
```

If the package wasn't installed correctly, try reinstalling it:

```bash
pip install --user LiveChessCloud
```

### 4. Upgrade to a Newer Environment

To avoid future compatibility issues, I strongly recommend upgrading to a current version of Ubuntu and Python. This will not only improve security and performance but also ensure that you continue to receive support and updates for your software.

I hope these steps resolve your issue. If you continue to encounter problems, please let me know, and we can explore further troubleshooting.

**Comment by eskopp** [comment]
Hi @galuel 

Your basic problem can only be solved by updating to a current version. This applies to Pip, python and also your Linux distro. 
In the 2 commits only 2 small problems with the imports are fixed which I noticed when testing your bug.
